name: default

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout2
        uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

  unittest:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout3
        uses: actions/checkout@v2
      - run: npm install
      - run: npm test

  e2etest:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout4
        uses: actions/checkout@v2
      - run: npm install
      - run: npm run test:e2e

  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout5
        uses: actions/checkout@v2
      - run: npm install
      - run: npm run docs

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout5
        uses: actions/checkout@v2
      - run: npm install
      - run: npm run checklint

